version: '3.8'

services:
  # Monolithic Database (Phase 1)
  mysql-monolith:
    image: mysql:8.0
    container_name: github-monolith
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_DATABASE: github_monolith
      MYSQL_USER: github_user
      MYSQL_PASSWORD: github_pass
    ports:
      - "3306:3306"
    volumes:
      - mysql_monolith_data:/var/lib/mysql
      - ../databases/monolith/schema.sql:/docker-entrypoint-initdb.d/01-schema.sql
    command: --default-authentication-plugin=mysql_native_password
    networks:
      - github-network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 20s
      retries: 10

  # SQL Proxy (Phase 1 - Simple HTTP API)
  sql-proxy:
    build:
      context: ../proxy
      dockerfile: Dockerfile
    container_name: github-sql-proxy
    ports:
      - "5000:5000"
    environment:
      - PROXY_HOST=0.0.0.0
      - PROXY_PORT=5000
      - LOG_LEVEL=INFO
      - MIGRATION_PHASE=1
    volumes:
      - ../proxy:/app
      - ../domains:/app/domains
    depends_on:
      mysql-monolith:
        condition: service_healthy
    networks:
      - github-network

networks:
  github-network:
    driver: bridge

volumes:
  mysql_monolith_data: